name: e_com_project_new
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0

  #flutter
  flutter_bloc: any
  flutter_screenutil: any
  font_awesome_flutter: any

  #api
  http: any

  #local database
  shared_preferences: any

  #text
  auto_size_text: any

  #amazing
  awesome_snackbar_content: ^0.1.3
  icons_plus: any
  carousel_slider: ^4.2.1

  #animations
  circular_reveal_animation: ^2.0.1
  animated_text_kit: ^4.2.2
  lottie: any

  #skeleton
  shimmer: ^3.0.0
  skeletonizer: ^1.1.1

  #google
  google_sign_in: any
  google_fonts: any

  #Bottom Nav Bar
  dot_navigation_bar: ^1.0.2
  animated_bottom_navigation_bar: ^1.3.3
  flashy_tab_bar2: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

